[env]
  port = 8383

[database]
  [database.info]
    name = "todos"
    host = "127.0.0.1"
    port = "5435"
    dialect = "postgres"
  [database.user]
    username = "postgres"
    password = "postgres"
  [database.time]
    timezone = "+08:00"
  [database.pool]
    max = 5
    min = 0
    acquire = 30000
    idle = 10000
